from pathlib import Path

from opendna.parser import parse_23andme, parse_source_file


def test_parse_23andme_skips_comments_and_blanks(fixtures_dir: Path) -> None:
    result = parse_23andme(fixtures_dir / "sample_23andme.txt")
    assert result["rs4680"] == "GG"
    assert result["rs1801133"] == "CT"
    assert len(result) == 11


def test_parse_23andme_handles_missing_file(tmp_path: Path) -> None:
    import pytest

    with pytest.raises(FileNotFoundError):
        parse_23andme(tmp_path / "does-not-exist.txt")


def test_parse_23andme_ignores_malformed_lines(tmp_path: Path) -> None:
    path = tmp_path / "d.txt"
    path.write_text("# header\nrs1\t1\t100\tAA\nnot-a-row\nrs2\t2\t200\tGG\n")
    result = parse_23andme(path)
    assert result == {"rs1": "AA", "rs2": "GG"}


def test_parse_23andme_preserves_no_call_genotype(fixtures_dir: Path) -> None:
    result = parse_23andme(fixtures_dir / "sample_23andme.txt")
    assert result["rs9999"] == "--"


def test_parse_23andme_accepts_string_path(fixtures_dir: Path) -> None:
    result = parse_23andme(str(fixtures_dir / "sample_23andme.txt"))
    assert "rs4680" in result


def test_parse_source_file_extracts_vendor_build_and_qc(fixtures_dir: Path) -> None:
    parsed = parse_source_file(fixtures_dir / "sample_23andme.txt")
    assert parsed.source.vendor == "23andMe"
    assert parsed.source.build == "GRCh37"
    assert parsed.source.unique_rsid_count == 11
    assert parsed.source.no_call_count == 1
    assert any(issue.code == "small-file" for issue in parsed.source.issues)
    assert any("consumer array" in note.lower() for note in parsed.source.blind_spots)


def test_parse_source_file_tracks_duplicates_and_ambiguous_calls(tmp_path: Path) -> None:
    path = tmp_path / "dna.txt"
    path.write_text(
        "# generated by MyHeritage\n"
        "# build 38\n"
        "rs1\t1\t100\tAA\n"
        "rs1\t1\t100\tAG\n"
        "rs2\t1\t101\tDD\n"
        "bad-row\n"
    )
    parsed = parse_source_file(path)
    assert parsed.source.vendor == "MyHeritage"
    assert parsed.source.build == "GRCh38"
    assert parsed.genotypes["rs1"] == "AG"
    assert parsed.source.duplicate_rsid_count == 1
    assert parsed.source.ambiguous_call_count == 1
    assert parsed.source.malformed_row_count == 1
